collections:
- name: kubernetes.core
- name: community.windows
- name: ansible.windows
- name: infra.windows_ops
  source: https://github.com/redhat-cop/infra.windows_ops.git
  type: git
  version: main
