collections:
- name: kubernetes.core
- name: community.windows
- name: ansible.windows
- name: infra.windows_ops
  source: https://github.com/rlopez133/infra.windows_ops.git
  type: git
  version: 001-fix-stig-rule-filter
