---
# EDA Rulebook: Compliance Auto-Remediation
# Triggers remediation when compliance alerts are received from Alertmanager

- name: Compliance Auto-Remediation
  hosts: all
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001

  rules:
    # Rule 1: CAT II violations - Auto-remediate
    - name: Remediate CAT II violations
      condition: >-
        event.alert.status == "firing" and
        event.alert.labels.category == "CAT2" and
        event.alert.labels.get("compliance.ocpvirt/eda-enabled", "false") == "true"
      action:
        run_job_template:
          name: Compliance-Remediate
          organization: "{{ aap_organization | default('Default') }}"
          job_args:
            extra_vars:
              target_vm: "{{ event.alert.labels.vm_name }}"
              target_namespace: "{{ event.alert.labels.namespace }}"
              control_id: "{{ event.alert.labels.control_id }}"
              trigger_source: "eda"
              cat_levels:
                - cat2
            limit: "{{ event.alert.labels.vm_name }}"

    # Rule 2: CAT III violations - Auto-remediate
    - name: Remediate CAT III violations
      condition: >-
        event.alert.status == "firing" and
        event.alert.labels.category == "CAT3" and
        event.alert.labels.get("compliance.ocpvirt/eda-enabled", "false") == "true"
      action:
        run_job_template:
          name: Compliance-Remediate
          organization: "{{ aap_organization | default('Default') }}"
          job_args:
            extra_vars:
              target_vm: "{{ event.alert.labels.vm_name }}"
              target_namespace: "{{ event.alert.labels.namespace }}"
              control_id: "{{ event.alert.labels.control_id }}"
              trigger_source: "eda"
              cat_levels:
                - cat3
            limit: "{{ event.alert.labels.vm_name }}"

    # Rule 3: CAT I violations - Notify only (no auto-remediation)
    - name: Notify on CAT I violations
      condition: >-
        event.alert.status == "firing" and
        event.alert.labels.category == "CAT1"
      action:
        run_job_template:
          name: Notify-Compliance-Team
          organization: "{{ aap_organization | default('Default') }}"
          job_args:
            extra_vars:
              notification_type: "critical"
              vm_name: "{{ event.alert.labels.vm_name }}"
              namespace: "{{ event.alert.labels.namespace }}"
              control_id: "{{ event.alert.labels.control_id }}"
              message: "Critical CAT I compliance violation detected. Manual remediation required."

    # Rule 4: Compliance score below threshold
    - name: Remediate low compliance score
      condition: >-
        event.alert.status == "firing" and
        event.alert.labels.alertname == "ComplianceScoreBelowThreshold" and
        event.alert.labels.get("compliance.ocpvirt/eda-enabled", "false") == "true"
      action:
        run_job_template:
          name: Compliance-Remediate
          organization: "{{ aap_organization | default('Default') }}"
          job_args:
            extra_vars:
              target_vm: "{{ event.alert.labels.vm_name }}"
              target_namespace: "{{ event.alert.labels.namespace }}"
              trigger_source: "eda"
              cat_levels:
                - cat2
                - cat3
            limit: "{{ event.alert.labels.vm_name }}"

    # Rule 5: Log all alerts for audit
    - name: Log all compliance alerts
      condition: >-
        event.alert.labels.alertname is match("Compliance.*")
      action:
        debug:
          msg: |
            Compliance Alert Received:
            - Alert: {{ event.alert.labels.alertname }}
            - Status: {{ event.alert.status }}
            - VM: {{ event.alert.labels.vm_name }}
            - Namespace: {{ event.alert.labels.namespace }}
            - Category: {{ event.alert.labels.category }}
            - Control: {{ event.alert.labels.control_id }}
