---
# EDA Rulebook: Compliance Auto-Remediation
# Triggers remediation when compliance alerts are received via event streams
#
# Event Stream Pattern:
# - Uses pg_listener source with name matching event stream
# - Event stream is bound at activation time via source_mappings
# - Alertmanager payloads arrive as event.payload with alerts array
#
# Auto-Remediation Toggles (set in activation extra_vars):
# - auto_remediate_cat1: false (CRITICAL - disabled by default)
# - auto_remediate_cat2: false (disabled by default)
# - auto_remediate_cat3: false (disabled by default)
#
# The toggles are passed to the job template which decides whether to remediate.

- name: Compliance Auto-Remediation
  hosts: all
  sources:
    - name: compliance-alerts
      ansible.eda.pg_listener: {}

  rules:
    # ==========================================================================
    # CAT I Alerts
    # ==========================================================================
    - name: CAT I Compliance Alert
      condition: >
        event.payload is defined and
        event.payload.status == "firing" and
        event.payload.commonLabels is defined and
        event.payload.commonLabels.category == "CAT1"
      action:
        run_job_template:
          name: "{{ remediation_job_template | default('Compliance-Remediate') }}"
          organization: "{{ eda_organization | default('Default') }}"
          job_args:
            extra_vars:
              target_vm: "{{ event['payload']['commonLabels']['vm_name'] | default('unknown') }}"
              target_namespace: "{{ event['payload']['commonLabels']['namespace'] | default('compliance') }}"
              category: "CAT1"
              alertname: "{{ event['payload']['commonLabels']['alertname'] | default('ComplianceCAT1Violation') }}"
              trigger_source: "eda"
              auto_remediate_cat1: "{{ auto_remediate_cat1 | default(false) }}"

    # ==========================================================================
    # CAT II Alerts
    # ==========================================================================
    - name: CAT II Compliance Alert
      condition: >
        event.payload is defined and
        event.payload.status == "firing" and
        event.payload.commonLabels is defined and
        event.payload.commonLabels.category == "CAT2"
      action:
        run_job_template:
          name: "{{ remediation_job_template | default('Compliance-Remediate') }}"
          organization: "{{ eda_organization | default('Default') }}"
          job_args:
            extra_vars:
              target_vm: "{{ event['payload']['commonLabels']['vm_name'] | default('unknown') }}"
              target_namespace: "{{ event['payload']['commonLabels']['namespace'] | default('compliance') }}"
              category: "CAT2"
              alertname: "{{ event['payload']['commonLabels']['alertname'] | default('ComplianceCAT2Violation') }}"
              trigger_source: "eda"
              auto_remediate_cat2: "{{ auto_remediate_cat2 | default(false) }}"

    # ==========================================================================
    # CAT III Alerts
    # ==========================================================================
    - name: CAT III Compliance Alert
      condition: >
        event.payload is defined and
        event.payload.status == "firing" and
        event.payload.commonLabels is defined and
        event.payload.commonLabels.category == "CAT3"
      action:
        run_job_template:
          name: "{{ remediation_job_template | default('Compliance-Remediate') }}"
          organization: "{{ eda_organization | default('Default') }}"
          job_args:
            extra_vars:
              target_vm: "{{ event['payload']['commonLabels']['vm_name'] | default('unknown') }}"
              target_namespace: "{{ event['payload']['commonLabels']['namespace'] | default('compliance') }}"
              category: "CAT3"
              alertname: "{{ event['payload']['commonLabels']['alertname'] | default('ComplianceCAT3Violation') }}"
              trigger_source: "eda"
              auto_remediate_cat3: "{{ auto_remediate_cat3 | default(false) }}"

    # ==========================================================================
    # Resolved Alerts (logging only)
    # ==========================================================================
    - name: Compliance Alert Resolved
      condition: >
        event.payload is defined and
        event.payload.status == "resolved" and
        event.payload.commonLabels is defined
      action:
        debug:
          msg: >
            Compliance Alert Resolved -
            VM: {{ event['payload']['commonLabels']['vm_name'] | default('unknown') }},
            Category: {{ event['payload']['commonLabels']['category'] | default('unknown') }}
