---
# EDA Rulebook: Compliance Auto-Remediation
# Triggers remediation when compliance alerts are received via event streams
#
# Event Stream Pattern:
# - Uses pg_listener source with name matching event stream
# - Event stream is bound at activation time via source_mappings
# - Alertmanager payloads arrive as event.payload with alerts array
#
# Payload Structure (from Alertmanager):
# event.payload.alerts[] - array of alert objects
# event.payload.alerts[].status - "firing" or "resolved"
# event.payload.alerts[].labels - alert labels (alertname, category, vm_name, etc.)
#
# Note: ansible-rulebook conditions use a specific DSL, not Jinja2 filters.
# Complex array filtering is handled in the action's extra_vars using Jinja2.

- name: Compliance Auto-Remediation
  hosts: all
  sources:
    - name: compliance-alerts
      ansible.eda.pg_listener:

  rules:
    # Rule 1: Process any firing compliance alert
    # The action extracts category-specific alerts and routes appropriately
    - name: Process compliance alerts
      condition: event.payload is defined and event.payload.status == "firing"
      action:
        run_job_template:
          name: Compliance-Remediate
          organization: "{{ eda_organization | default('Default') }}"
          job_args:
            extra_vars:
              target_vm: "{{ event.payload.commonLabels.vm_name | default('') }}"
              target_namespace: "{{ event.payload.commonLabels.namespace | default('') }}"
              control_id: "{{ event.payload.commonLabels.control_id | default('') }}"
              category: "{{ event.payload.commonLabels.category | default('') }}"
              alertname: "{{ event.payload.commonLabels.alertname | default('') }}"
              trigger_source: "eda"
              auto_remediate_cat1: "{{ auto_remediate_cat1 | default(false) }}"
              auto_remediate_cat2: "{{ auto_remediate_cat2 | default(true) }}"
              auto_remediate_cat3: "{{ auto_remediate_cat3 | default(true) }}"

    # Rule 2: Log resolved alerts
    - name: Log resolved compliance alerts
      condition: event.payload is defined and event.payload.status == "resolved"
      action:
        debug:
          msg: |
            Compliance Alert Resolved:
            - Alert: {{ event.payload.commonLabels.alertname | default('unknown') }}
            - VM: {{ event.payload.commonLabels.vm_name | default('unknown') }}
            - Category: {{ event.payload.commonLabels.category | default('unknown') }}

    # Rule 3: Catch-all for any event (audit logging)
    - name: Audit log all events
      condition: event.payload is defined
      action:
        debug:
          msg: |
            Event Received:
            - Status: {{ event.payload.status | default('unknown') }}
            - Receiver: {{ event.payload.receiver | default('unknown') }}
            - Group Labels: {{ event.payload.groupLabels | default({}) }}
